name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - testing

permissions:
  contents: write  # still good to have, but won't be used since we're switching to PAT

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}  # 👈 using your PAT here
          publish_dir: ./dist
